### ISSUE TITLE
[ERROR] cannot call listapplication

### ISSUE THREAD

**Issue by adashen** [Azure-Samples/azure-iot-central-samples-csharp#1]
{"error":{"code":"InvalidRequest","message":"This API cannot be called for the application custom-fkzaspnngw.azureiotcentral.com. If you contact support, please include the following information. Request ID: XXXX, 
Time: Wed, 13 Nov 2019 08:44:28 GMT.","requestId":"XXXX","time":"Wed, 13 Nov 2019 08:44:28 GMT"}}

**Comment by yang-hai-feng** [comment]
preview API was retired and list application can be done through ARM API only.
